add_newline = true

format = """
[â”Œâ”€â”€â”€](bold green)\
[\\($username[@](white)[ãƒ•ã‚£ã‚¸ãƒƒã‚¯ã‚¹](blue)[PC](white)\\)-[\\[](white)$directory[\\]](white)](green)$cmd_duration
[â”‚(\
$git_branch\
$git_commit\
$git_state\
$git_metrics\
$git_status\
$docker_context\
$cmake\
$dart\
$deno\
$golang\
$nodejs\
$php\
$python\
$rust\
$swift\
$vlang\
$status\
$shell\
$package)](bold green)
[â””â”€](bold green) $character"""

[character]
success_symbol = "[Î»](white)"
error_symbol = "[Î»](red)"

[directory]
style = "white"
format = "[$path]($style)[$read_only]($read_only_style)"

[hostname]
ssh_only = false
style = "blue"
format =  "[$hostname]($style)"
disabled = false

[username]
style_user = "blue"
style_root = "red"
format = "[$user]($style)"
disabled = false
show_always = true

[cmd_duration]
format = ": [$duration]($style)"
show_notifications = true

[git_branch]
style = "green"
format = "[$symbol$branch ]($style)"
symbol = " [î‚ ](#AAAAAA) "

[package]
format = " | [$symbol$version]($style)"

[rust]
format = " [$symbol($version)]($style)"

[php]
format = " [$symbol($version)]($style)"

[deno]
format = " [$symbol($version)]($style)"

[nodejs]
format = " [$symbol($version)]($style)"
symbol = "ðŸ¤– "

[python]
format = " [$symbol($version)]($style)"

[docker_context]
format = " [$symbol($version)]($style)"
